/**
 * Deterministic RNG. Every generator takes a seed so a result can be
 * reproduced, shared by URL, or regenerated by bumping the seed.
 */
export function createRng(seed = 1) {
  let state = (typeof seed === 'string' ? hashString(seed) : seed) || 1
  return function next() {
    // Mulberry32 — small, fast, good enough spread for content generation.
    state = (state + 0x6d2b79f5) | 0
    let t = state
    t = Math.imul(t ^ (t >>> 15), t | 1)
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61)
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296
  }
}

export function hashString(str) {
  let h = 2166136261
  for (let i = 0; i < str.length; i += 1) {
    h ^= str.charCodeAt(i)
    h = Math.imul(h, 16777619)
  }
  return h >>> 0
}

export const pick = (rng, list) => list[Math.floor(rng() * list.length)]

export const pickMany = (rng, list, count) => {
  const pool = [...list]
  const out = []
  while (out.length < count && pool.length) {
    out.push(pool.splice(Math.floor(rng() * pool.length), 1)[0])
  }
  return out
}

export const randomInt = (rng, min, max) => Math.floor(rng() * (max - min + 1)) + min

export const shuffle = (rng, list) => {
  const arr = [...list]
  for (let i = arr.length - 1; i > 0; i -= 1) {
    const j = Math.floor(rng() * (i + 1))
    ;[arr[i], arr[j]] = [arr[j], arr[i]]
  }
  return arr
}

/**
 * Fills a template like "{adjective} {noun}" from a bank of word lists,
 * never repeating the same value twice inside one string.
 */
export function fillTemplate(rng, template, bank, extras = {}) {
  const used = new Set()
  return template.replace(/\{(\w+)\}/g, (match, key) => {
    if (extras[key] !== undefined) return extras[key]
    const list = bank[key]
    if (!list || !list.length) return match
    for (let attempt = 0; attempt < 12; attempt += 1) {
      const value = pick(rng, list)
      if (!used.has(value)) {
        used.add(value)
        return value
      }
    }
    return pick(rng, list)
  })
}

/** A fresh seed for the "generate again" button. */
export const newSeed = () => Math.floor(Math.random() * 2 ** 31)
